# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server/proto/meter_ingest.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'server/proto/meter_ingest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fserver/proto/meter_ingest.proto\x12\x0bmetering.v1\"l\n\x14SubmitReadingRequest\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x13\n\x0brecorded_at\x18\x02 \x01(\t\x12\x18\n\x0breading_kwh\x18\x03 \x01(\x01H\x00\x88\x01\x01\x42\x0e\n\x0c_reading_kwh\"=\n\x15SubmitReadingResponse\x12\x12\n\nreading_id\x18\x01 \x01(\x03\x12\x10\n\x08meter_id\x18\x02 \x01(\x03\x32h\n\x0eMeterIngestion\x12V\n\rSubmitReading\x12!.metering.v1.SubmitReadingRequest\x1a\".metering.v1.SubmitReadingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.proto.meter_ingest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITREADINGREQUEST']._serialized_start=48
  _globals['_SUBMITREADINGREQUEST']._serialized_end=156
  _globals['_SUBMITREADINGRESPONSE']._serialized_start=158
  _globals['_SUBMITREADINGRESPONSE']._serialized_end=219
  _globals['_METERINGESTION']._serialized_start=221
  _globals['_METERINGESTION']._serialized_end=325
# @@protoc_insertion_point(module_scope)
