# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from server.proto import meter_ingest_pb2 as server_dot_proto_dot_meter__ingest__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in server/proto/meter_ingest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeterIngestionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitReading = channel.unary_unary(
                '/metering.v1.MeterIngestion/SubmitReading',
                request_serializer=server_dot_proto_dot_meter__ingest__pb2.SubmitReadingRequest.SerializeToString,
                response_deserializer=server_dot_proto_dot_meter__ingest__pb2.SubmitReadingResponse.FromString,
                _registered_method=True)


class MeterIngestionServicer:
    """Missing associated documentation comment in .proto file."""

    def SubmitReading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeterIngestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitReading': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitReading,
                    request_deserializer=server_dot_proto_dot_meter__ingest__pb2.SubmitReadingRequest.FromString,
                    response_serializer=server_dot_proto_dot_meter__ingest__pb2.SubmitReadingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metering.v1.MeterIngestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metering.v1.MeterIngestion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeterIngestion:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metering.v1.MeterIngestion/SubmitReading',
            server_dot_proto_dot_meter__ingest__pb2.SubmitReadingRequest.SerializeToString,
            server_dot_proto_dot_meter__ingest__pb2.SubmitReadingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
